apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sl1t3yl0i-python
  janus-idp.io/tekton: sl1t3yl0i-python
  backstage.io/kubernetes-id: sl1t3yl0i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sl1t3yl0i-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
